import type { BookingPolicy, Facility, FacilityCategory, Role, SystemSettings, WeeklySchedule } from "@/domain/types";

/* ───────────────────────── Global policy ───────────────────────── */

export const GLOBAL_POLICY: BookingPolicy = {
  window: { advanceDays: 7, minLeadMinutes: 15 },
  limits: { perDay: 2, perWeek: 6, maxActive: 3 },
  fairness: {
    scope: "facility",
    maxConsecutive: 1,
    restMinutes: 0,
    applyToParticipants: true,
    linkedGroups: { enabled: false, lookbackDays: 30, minSharedSessions: 3, action: "block" },
  },
  participants: { required: false, min: 1, max: 20 },
  cancellation: { freeUntilMinutes: 120, lateCountsAsStrike: false },
  checkIn: { opensMinutesBefore: 15, graceMinutes: 15, autoNoShow: true },
  noShow: {
    strikeExpiryDays: 60,
    ladder: [
      { strikes: 1, action: "warning" },
      { strikes: 2, action: "final_warning" },
      { strikes: 3, action: "restrict", restrictDays: 14 },
    ],
  },
  waitlist: { enabled: true, maxPerSession: 10, claimMinutes: 30 },
  approval: { required: false },
  campus: { maxActiveBookings: 5, maxActiveWaitlists: 3 },
};

export const SETTINGS: SystemSettings = {
  universityName: "Badya University",
  productName: "Badya Spaces",
  timezone: "Africa/Cairo",
  weekStartsOn: 6,
  qrRotationSeconds: 30,
  sessionTimeoutMinutes: 30,
  bookingRateLimitPerMinute: 10,
  reminderMinutesBefore: 60,
  supportEmail: "spaces@badya.edu.eg",
  allowedEmailDomains: ["badya.edu.eg"],
  maxDevicesPerStudent: 1,
};

/* ───────────────────────── Roles ───────────────────────── */

const STUDENT_PERMS = ["facility.view", "booking.create", "booking.cancel.own", "waitlist.join"] as const;
const STAFF_PERMS = ["facility.view", "schedule.view", "checkin.perform", "noshow.mark", "facility.report_issue", "facility.close_temporarily"] as const;
const ADMIN_PERMS = [
  ...STAFF_PERMS,
  "facility.manage",
  "category.manage",
  "booking.manage",
  "student.manage",
  "policy.manage",
  "maintenance.manage",
  "waitlist.manage",
  "fairness.review",
  "analytics.view",
  "audit.view",
  "staff.manage",
  "settings.manage",
] as const;

export const ROLES: Role[] = [
  { key: "student", name: "Student", description: "Books facilities for themselves and their teammates.", permissions: [...STUDENT_PERMS] },
  { key: "staff", name: "Facility staff", description: "Runs assigned facilities day to day: check-in, no-shows, issues.", permissions: [...STAFF_PERMS] },
  { key: "admin", name: "Administrator", description: "Manages facilities, rules, bookings and students.", permissions: [...ADMIN_PERMS] },
  { key: "super_admin", name: "Super admin", description: "Full system control, including roles, security and global policy.", permissions: [...ADMIN_PERMS, "policy.global.manage", "admin.manage", "role.manage", "security.manage"] },
];

/* ───────────────────────── Categories ───────────────────────── */

export const CATEGORIES: FacilityCategory[] = [
  {
    id: "cat_racket",
    name: "Racket Sports",
    nameAr: "رياضات المضرب",
    description: "The tennis court and the two padel courts.",
    ar: { description: "ملعب التنس وملعبين البادل." },
    kind: "sports",
    motif: "padel",
    color: "#B5642E",
    sortOrder: 1,
    active: true,
    policy: {
      window: { advanceDays: 3, minLeadMinutes: 20 },
      limits: { perDay: 1, perWeek: 4, maxActive: 2 },
      fairness: { scope: "category", maxConsecutive: 1, restMinutes: 60, applyToParticipants: true, linkedGroups: { enabled: true, lookbackDays: 30, minSharedSessions: 3, action: "flag" } },
      participants: { required: true, min: 2, max: 4 },
      cancellation: { freeUntilMinutes: 120, lateCountsAsStrike: false },
      waitlist: { claimMinutes: 30 },
    },
  },
  {
    id: "cat_team",
    name: "Team Sports",
    nameAr: "الرياضات الجماعية",
    description: "The football pitch and the volleyball court.",
    ar: { description: "ملعب كرة القدم وملعب الكرة الطائرة." },
    kind: "sports",
    motif: "football",
    color: "#2F7A4F",
    sortOrder: 2,
    active: true,
    policy: {
      window: { advanceDays: 3, minLeadMinutes: 30 },
      limits: { perDay: 1, perWeek: 3, maxActive: 2 },
      fairness: { scope: "category", maxConsecutive: 1, restMinutes: 120, applyToParticipants: true, linkedGroups: { enabled: true, lookbackDays: 30, minSharedSessions: 3, action: "block" } },
      participants: { required: true, min: 6, max: 14 },
      cancellation: { freeUntilMinutes: 180, lateCountsAsStrike: true },
      waitlist: { maxPerSession: 8, claimMinutes: 30 },
    },
  },
  {
    id: "cat_activity",
    name: "Activity Center",
    nameAr: "الأكتيفيتي سنتر",
    description: "Ping-pong, billiards and air hockey tables.",
    ar: { description: "ترابيزات البينج بونج والبلياردو والإير هوكي." },
    kind: "recreation",
    motif: "billiards",
    color: "#6A4C93",
    sortOrder: 3,
    active: true,
    policy: {
      window: { advanceDays: 2, minLeadMinutes: 10 },
      limits: { perDay: 2, perWeek: 6, maxActive: 2 },
      fairness: { scope: "facility", maxConsecutive: 1, restMinutes: 30 },
      participants: { required: false, min: 1, max: 4 },
      cancellation: { freeUntilMinutes: 30, lateCountsAsStrike: false },
      waitlist: { claimMinutes: 15 },
    },
  },
];

/* ───────────────────────── Facilities ───────────────────────── */

const daily = (open: string, close: string): WeeklySchedule => Array.from({ length: 7 }, () => ({ open, close }));
const weekdays = (open: string, close: string, fri: [string, string] | null, sat: [string, string] | null): WeeklySchedule => [
  { open, close },
  { open, close },
  { open, close },
  { open, close },
  { open, close },
  fri ? { open: fri[0], close: fri[1] } : null,
  sat ? { open: sat[0], close: sat[1] } : null,
];

const CREATED = "2026-06-01T09:00:00.000Z";
const ALL_STUDENTS: Facility["access"] = { audiences: ["undergraduate", "postgraduate"], faculties: null, minYear: null };
const SPORTS = { building: "Sports Courts", buildingAr: "الملاعب الرياضية" };
const ACTIVITY = { building: "Activity Center", buildingAr: "الأكتيفيتي سنتر" };
/** Activity Center hours — closed on Fridays. */
const ACTIVITY_HOURS = weekdays("10:00", "20:00", null, ["10:00", "20:00"]);

export const FACILITIES: Facility[] = [
  {
    id: "f_tennis",
    name: "Tennis Court",
    nameAr: "ملعب التنس",
    categoryId: "cat_racket",
    shortDescription: "Floodlit hard court for singles or doubles.",
    description: "The university tennis court. Book for singles or doubles and list the university IDs of everyone playing.",
    location: { building: SPORTS.building, area: "Tennis court", mapX: 81, mapY: 38 },
    media: { motif: "tennis", accent: "#3F7FA6" },
    mode: "exclusive",
    units: 1,
    unitLabel: "court",
    capacity: 4,
    sessionMinutes: 60,
    turnoverMinutes: 0,
    schedule: daily("08:00", "22:00"),
    amenities: ["floodlights", "water", "seating"],
    rules: ["Tennis shoes only.", "Singles or doubles — up to 4 players.", "Please collect all balls before you leave."],
    policy: {},
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ملعب تنس بإضاءة ليلية للفردي أو الزوجي.",
      description: "ملعب التنس في الجامعة. احجز للفردي أو الزوجي واكتب الأرقام الجامعية لكل اللاعبين.",
      rules: ["حذاء تنس فقط.", "فردي أو زوجي — حتى 4 لاعبين.", "برجاء جمع كل الكور قبل ما تمشي."],
      unitLabel: "ملعب",
      building: SPORTS.buildingAr,
      area: "ملعب التنس",
    },
  },
  {
    id: "f_padel",
    name: "Padel Courts",
    nameAr: "ملاعب البادل",
    categoryId: "cat_racket",
    shortDescription: "Two padel courts — you get one when you book.",
    description: "Two glass-walled padel courts. Each booking reserves one court; the court number appears on your ticket. Sessions are 90 minutes.",
    location: { building: SPORTS.building, area: "Padel courts", mapX: 77, mapY: 47 },
    media: { motif: "padel", accent: "#2F8C84" },
    mode: "exclusive",
    units: 2,
    unitLabel: "court",
    capacity: 4,
    sessionMinutes: 90,
    turnoverMinutes: 0,
    schedule: daily("08:00", "22:00"),
    amenities: ["floodlights", "water"],
    rules: ["Doubles: up to 4 players.", "No hanging on the glass walls."],
    policy: {},
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ملعبين بادل — بيتحدد لك ملعب وقت الحجز.",
      description: "ملعبين بادل بحوائط زجاج. كل حجز بياخد ملعب واحد، ورقم الملعب بيظهر في التذكرة. مدة الحجز 90 دقيقة.",
      rules: ["زوجي: حتى 4 لاعبين.", "ممنوع التعلّق على الحوائط الزجاج."],
      unitLabel: "ملعب",
      building: SPORTS.buildingAr,
      area: "ملاعب البادل",
    },
  },
  {
    id: "f_football",
    name: "Football Pitch",
    nameAr: "ملعب كرة القدم",
    categoryId: "cat_team",
    shortDescription: "Floodlit pitch — list 6 to 14 players.",
    description: "The university football pitch. List the university IDs of 6 to 14 players; everyone listed follows the same booking limits.",
    location: { building: SPORTS.building, area: "Football pitch", mapX: 72, mapY: 30 },
    media: { motif: "football", accent: "#2F7A4F" },
    mode: "exclusive",
    units: 1,
    unitLabel: "pitch",
    capacity: 14,
    sessionMinutes: 60,
    turnoverMinutes: 0,
    schedule: daily("08:00", "22:00"),
    amenities: ["floodlights", "water", "seating"],
    rules: ["Football boots or turf shoes only.", "Bring your own ball.", "Leave the pitch on time for the next group."],
    policy: {},
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ملعب بإضاءة ليلية — من 6 لـ 14 لاعب.",
      description: "ملعب كرة القدم في الجامعة. اكتب الأرقام الجامعية لـ 6 إلى 14 لاعب، وكل اللي في القائمة بتنطبق عليهم نفس حدود الحجز.",
      rules: ["جزمة كورة أو حذاء نجيل صناعي فقط.", "هات الكورة بتاعتك.", "اخرج من الملعب في ميعادك عشان المجموعة اللي بعدك."],
      unitLabel: "ملعب",
      building: SPORTS.buildingAr,
      area: "ملعب كرة القدم",
    },
  },
  {
    id: "f_volleyball",
    name: "Volleyball Court",
    nameAr: "ملعب الكرة الطائرة",
    categoryId: "cat_team",
    shortDescription: "Outdoor court — list 6 to 12 players.",
    description: "The university volleyball court. List the university IDs of 6 to 12 players.",
    location: { building: SPORTS.building, area: "Volleyball court", mapX: 85, mapY: 30 },
    media: { motif: "volleyball", accent: "#C0892B" },
    mode: "exclusive",
    units: 1,
    unitLabel: "court",
    capacity: 12,
    sessionMinutes: 60,
    turnoverMinutes: 0,
    schedule: daily("08:00", "22:00"),
    amenities: ["floodlights", "water"],
    rules: ["Sports shoes only.", "Up to 12 players."],
    policy: { participants: { min: 6, max: 12 } },
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ملعب مكشوف — من 6 لـ 12 لاعب.",
      description: "ملعب الكرة الطائرة في الجامعة. اكتب الأرقام الجامعية لـ 6 إلى 12 لاعب.",
      rules: ["حذاء رياضي فقط.", "حتى 12 لاعب."],
      unitLabel: "ملعب",
      building: SPORTS.buildingAr,
      area: "ملعب الكرة الطائرة",
    },
  },
  {
    id: "f_pingpong",
    name: "Ping-Pong Tables",
    nameAr: "ترابيزات البينج بونج",
    categoryId: "cat_activity",
    shortDescription: "Two tables, 30-minute sessions.",
    description: "Two ping-pong tables in the Activity Center. Each booking reserves one table for 30 minutes. Rackets and balls are available at the desk.",
    location: { building: ACTIVITY.building, mapX: 47, mapY: 56 },
    media: { motif: "tabletennis", accent: "#3D6FB0" },
    mode: "exclusive",
    units: 2,
    unitLabel: "table",
    capacity: 4,
    sessionMinutes: 30,
    turnoverMinutes: 0,
    schedule: ACTIVITY_HOURS,
    amenities: ["ac", "equipment", "seating"],
    rules: ["Up to 4 players per table.", "Return rackets and balls to the desk."],
    policy: {},
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ترابيزتين، مدة الحجز 30 دقيقة.",
      description: "ترابيزتين بينج بونج في الأكتيفيتي سنتر. كل حجز بياخد ترابيزة واحدة لمدة 30 دقيقة. المضارب والكور موجودة عند المكتب.",
      rules: ["حتى 4 لاعبين على الترابيزة.", "رجّع المضارب والكور للمكتب."],
      unitLabel: "ترابيزة",
      building: ACTIVITY.buildingAr,
    },
  },
  {
    id: "f_billiards",
    name: "Billiards Table",
    nameAr: "ترابيزة البلياردو",
    categoryId: "cat_activity",
    shortDescription: "One table, 45-minute sessions.",
    description: "The billiards table in the Activity Center. Cues and balls are available at the desk.",
    location: { building: ACTIVITY.building, mapX: 49, mapY: 53 },
    media: { motif: "billiards", accent: "#2F6B4A" },
    mode: "exclusive",
    units: 1,
    unitLabel: "table",
    capacity: 4,
    sessionMinutes: 45,
    turnoverMinutes: 0,
    schedule: ACTIVITY_HOURS,
    amenities: ["ac", "equipment", "seating"],
    rules: ["Up to 4 players.", "No sitting on the table.", "Return cues to the rack."],
    policy: {},
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ترابيزة واحدة، مدة الحجز 45 دقيقة.",
      description: "ترابيزة البلياردو في الأكتيفيتي سنتر. العصيان والكور موجودة عند المكتب.",
      rules: ["حتى 4 لاعبين.", "ممنوع القعدة على الترابيزة.", "رجّع العصيان مكانها."],
      unitLabel: "ترابيزة",
      building: ACTIVITY.buildingAr,
    },
  },
  {
    id: "f_airhockey",
    name: "Air Hockey Table",
    nameAr: "ترابيزة الإير هوكي",
    categoryId: "cat_activity",
    shortDescription: "One table, quick 20-minute games.",
    description: "The air hockey table in the Activity Center — quick 20-minute sessions for two players.",
    location: { building: ACTIVITY.building, mapX: 45, mapY: 59 },
    media: { motif: "airhockey", accent: "#B23A48" },
    mode: "exclusive",
    units: 1,
    unitLabel: "table",
    capacity: 2,
    sessionMinutes: 20,
    turnoverMinutes: 0,
    schedule: ACTIVITY_HOURS,
    amenities: ["ac", "seating"],
    rules: ["Two players.", "Keep the pucks and mallets on the table."],
    policy: { participants: { max: 2 } },
    access: ALL_STUDENTS,
    status: "active",
    createdAt: CREATED,
    updatedAt: CREATED,
    ar: {
      shortDescription: "ترابيزة واحدة، ماتشات سريعة 20 دقيقة.",
      description: "ترابيزة الإير هوكي في الأكتيفيتي سنتر — حجز سريع 20 دقيقة للاعبين اتنين.",
      rules: ["لاعبين اتنين.", "خلّي البَك والمضارب على الترابيزة."],
      unitLabel: "ترابيزة",
      building: ACTIVITY.buildingAr,
    },
  },
];

export const FACULTIES = [
  "Computer Science",
  "Engineering",
  "Architecture & Design",
  "Business Administration",
  "Medicine",
  "Dentistry",
  "Pharmacy",
  "Physical Therapy",
  "Mass Communication",
];

export const PROGRAMS: Record<string, string[]> = {
  "Computer Science": ["Artificial Intelligence", "Software Engineering", "Data Science", "Cybersecurity"],
  Engineering: ["Mechatronics", "Civil Engineering", "Electrical Engineering", "Biomedical Engineering"],
  "Architecture & Design": ["Architecture", "Interior Design", "Urban Design"],
  "Business Administration": ["Finance", "Marketing", "Business Analytics"],
  Medicine: ["Medicine & Surgery"],
  Dentistry: ["Oral & Dental Medicine"],
  Pharmacy: ["Clinical Pharmacy", "Pharmaceutical Sciences"],
  "Physical Therapy": ["Physical Therapy"],
  "Mass Communication": ["Journalism", "Digital Media", "Public Relations"],
};
